class CSXConstants:

    ARTICLE_TYPE = "article"
    HUB_TYPE = "hub"

    ARTICLE_SUB_ID = 1
    HUB_SUB_ID = 5

    USER_SUBMISSION_PREFIX = "USUB-"

    INFERENCE_VERSION = "INFERENCE"
    USER_VERSION = "USER"

    UNPROCESS_AUTHOR = 0
    ERROR_AUTHOR     = 1

    NOISE_AUTHOR     = 2

    USER_REMOVED     = 3

    MAX_DOC_TITLE = 255
    MAX_DOC_VENUE = 255
    MAX_DOC_VENTYPE = 20
    MAX_DOC_PAGES = 20
    MAX_DOC_PUBL = 100
    MAX_DOC_PUBADDR = 100
    MAX_DOC_TECH = 100

    MAX_AUTH_NAME = 100
    MAX_AUTH_AFFIL = 255
    MAX_AUTH_ADDR = 255
    MAX_AUTH_EMAIL = 100

    MAX_KEYWORD = 100

    MAX_ACK_NAME = 255
    MAX_ACK_ETYPE = 20
    MAX_URL = 255
    MAX_CONV_TRACE = 255